--- 
addons: 
  ssh_known_hosts: advhater.ru
before_deploy:
- openssl aes-256-cbc ...
 - eval "$(ssh-agent -s)"
 - chmod 600 .deploy_rsa.enc
 - ssh-add .deploy_rsa.enc
deploy: 
  provider: script
  skip_cleanup: true
install: true
language: node_js
script: scp -r $TRAVIS_BUILD_DIR/static  evv@advhater.ru:/home/evv/test
