--- 
addons: 
  ssh_known_hosts: advhater.ru
before_deploy: 
  - "openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in tr_rsa_valid.enc -out /tmp/tr_rsa_valid -d"
  - "eval \"$(ssh-agent -s)\""
  - "chmod 600 /tmp/tr_rsa_valid"
  - "ssh-add /tmp/tr_rsa_valid"
deploy: 
  provider: script
  skip_cleanup: true
install: true
language: node_js
script: "scp -r $TRAVIS_BUILD_DIR/static evv@advhater.ru:/home/evv/test"
