addons:
  ssh_known_hosts: advhater.ru
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- head deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
install: true
language: node_js
script: scp -r $TRAVIS_BUILD_DIR/static  evv@advhater.ru:/home/evv/test
before_install:
- openssl aes-256-cbc -K $encrypted_a4d1577586d3_key -iv $encrypted_a4d1577586d3_iv in deploy_rsa.enc -out deploy_rsa -d
- head deploy_rsa
